### ISSUE TITLE
Cannot Install on Laravel 8.34.0

### ISSUE THREAD

**Issue by YutaInouePH** [larsjanssen6/underconstruction#111]
Good day! 

I've tried installing this package on Laravel v8.34.0
I'm able to use this package on other versions, except for the one above. 

Here's the screenshot for reference.
![image](https://user-images.githubusercontent.com/58018461/114271182-17f3a400-9a4b-11eb-8865-6736e072ec20.png)

**Comment by stefanschindler** [comment]
I got the same problem with Laravel v8.40

**Comment by YutaInouePH** [comment]
Using PHP7.4 solved the problem. 
Sorry for the fuss.
