### ISSUE TITLE
Add button for showing/hidding password.

### ISSUE THREAD

**Issue by larsjanssen6** [larsjanssen6/underconstruction#21]
I would like to implement this feature:

Make a toggle button that shows/hides the password in vue.js. So instead of showing
the numbers show a star or something. 

Within this file:

https://github.com/larsjanssen6/underconstruction/blob/master/resources/assets/UnderConstruction.vue

**Comment by vijaygomathinayagam** [comment]
i will take this

**Comment by larsjanssen6** [comment]
@VijayGomathi thanks

**Comment by vijaygomathinayagam** [comment]
I am getting this error. I don't know how to install
![package name](https://user-images.githubusercontent.com/31568585/31380234-57f0dee6-adce-11e7-8d69-dfad1583b53e.PNG)

**Comment by larsjanssen6** [comment]
@VijayGomathi yes it's not released yet. You should fork or clone it. And put it in a fresh Laravel project yourself.

**Comment by larsjanssen6** [comment]
@VijayGomathi it's now possible to run the command:

```bash
composer require larsjanssen6/underconstruction
```

**Comment by vijaygomathinayagam** [comment]
![undercontruction](https://user-images.githubusercontent.com/31568585/31382110-36874596-add4-11e7-9fd4-0da7c875f179.PNG)
 I am getting this error now. Very sorry it is very difficult for me to proceed.

**Comment by larsjanssen6** [comment]
@VijayGomathi no problem, are you within a fresh Laravel 5.5 project?

**Comment by vijaygomathinayagam** [comment]
@larsjanssen6 I forked Laravel from github. Please tell me the next step

**Comment by djsheva** [comment]
@larsjanssen6 done in pull request #22 
Please, check

**Comment by larsjanssen6** [comment]
@djsheva thanks will look to it in a few days!
