### ISSUE TITLE
Add tests with Laravel dusk 

### ISSUE THREAD

**Issue by larsjanssen6** [larsjanssen6/underconstruction#25]
Hi,

I'm using `Vue.js` and `Laravel` in this package. I would like to implement some tests with Laravel dusk. Right now I can't test some things. 

For example:

- After a successful login test the redirect url. (Right now I cannot do this because I make a post request with `axios` to check the code and then I redirect)

- When user has disabled throttle in `config.php` file, no attempt messages should be visible. 

- When the `hide button` is clicked no numbers should be visible. 

 - When the `wrong code` is entered the class `wrong_code` should be visible. 

 - When the `correct code` is entered the class `success_code` should be visible. 

Would be awesome to implement this in my package!

https://laravel.com/docs/5.5/dusk

Obviously you could add/improve my tests that I have right now. 

Thanks a lot!

**Comment by twosocks** [comment]
I'm not sure but I think you can't integrate Laravel Dusk in this project.
Dusk (or other browsers test) emulates user actions and it needs the URL entry point to work.
Dusk tests websites (and the plugin used) but at the end tests belong to the Laravel project not to the plugins.
Maybe some Dusk tests can be used when the package is installed on a Laravel project, but not during the developing stage like unit test

**Comment by Drivez** [comment]
I can look into this, looks like a cool project.
I will try to implement Dusk on this also
