### ISSUE TITLE
Use link from config file instead of hardcoded

### ISSUE THREAD

**Issue by larsjanssen6** [larsjanssen6/underconstruction#27]
Hi,

Right now in my `under construction` package I use this link `/under/construction`.

It would be awesome if the user could determine this link by it self. The user has to set this link in `config.php`. 

Please update my tests aswel. 

Thanks a lot.

**Comment by Skowt** [comment]
Looking into this now

**Comment by larsjanssen6** [comment]
@Skowt thx

**Comment by Skowt** [comment]
Just to confirm, it looks like you've got 3 endpoints:
```
POST - /under/check
GET - /under/construction
GET - /under/js
```

Are you wanting all 3 to be configurable or just the `/under/` section or specifically just the endpoint `/under/construction`?

**Comment by larsjanssen6** [comment]
@Skowt only /under/construction please.

**Comment by Skowt** [comment]
I believe I have it working but I'm struggling to get the package running locally instead of pulling it via `composer require larsjanssen6/underconstruction`. Could you tell me how you run a local version for dev work?

**Comment by larsjanssen6** [comment]
@Skowt

First fork my repo. 

I'm always making a packages folder in a fresh Laravel installation. Then clone the forked repo there.  In my `composer.json` file (from fresh laravel installation):


```
"psr-4": {
    "App\\": "app/",
    "LarsJanssen\\UnderConstruction\\": "packages/LarsJanssen/underconstruction/src"
}
```

Run `composer dumpautoload`

And register the `service provider` (`        LarsJanssen\UnderConstruction\UnderConstructionServiceProvider::class,`) in `app.php` (for laravel 5.5 aswel).

When you've made your changes push to git. And make a pull request. 

I recommend this video: https://laracasts.com/series/how-do-i/episodes/20

Hope that helps?

**Comment by Skowt** [comment]
Awesome, thanks @larsjanssen6! I'll try get to this tonight (South African time)

**Comment by larsjanssen6** [comment]
@Skowt  thanks if you've any questions let me know.

**Comment by Skowt** [comment]
I see David's gone and submitted a PR. Left a comment but otherwise, going to abandon my PR 🙂

**Comment by larsjanssen6** [comment]
@Skowt that's cool. Thanks!
