### ISSUE TITLE
[Question] Pin Code Length

### ISSUE THREAD

**Issue by brysem** [larsjanssen6/underconstruction#37]
Hoi,

Love the idea of this package.
Is there a reason why the package only supports a pin code of 4 numbers and not 6 for example?

I am curious as to why it has been restricted to a specific amount of numbers.
I would be willing to make a PR to adjust it so that the user can self decide the length.

**Comment by larsjanssen6** [comment]
Hmmm interesting!

Would love to see a pull request for that (with tests 🥇)!
