### ISSUE TITLE
Feature request: keyboard support

### ISSUE THREAD

**Issue by defji** [larsjanssen6/underconstruction#41]
It wold be nice if i could enter PIN with keyboard

**Comment by larsjanssen6** [comment]
That's already possible!

**Comment by paneidos** [comment]
It works in Chrome, but not in Firefox.

**Comment by larsjanssen6** [comment]
@paneidos will take a look at that.

**Comment by paneidos** [comment]
I think I have a solution, I'll send you a PR.
