### ISSUE TITLE
Invalid code

### ISSUE THREAD

**Issue by sweebee** [larsjanssen6/underconstruction#43]
It keeps saying im entering an invalid code. I ran:

```php artisan code:set 1234```

result: ```Code: "1234" is set successfully.```

but it keeps getting red when entering the code.

**Comment by larsjanssen6** [comment]
@sweebee please remove the old code in .env file. Look into your network tab what the error is 👍

**Comment by sweebee** [comment]
Thanks that works, but now on a online server the under construction page won't show up. Locally it works fine.

**Comment by larsjanssen6** [comment]
@sweebee Please look into your network tab when you submit the code. What is the response error?

**Comment by sweebee** [comment]
got it, my bad. didn't refresh the route cache.

**Comment by kieranbarlow** [comment]
I have the same issue - the response I get back is 

{"too_many_attempts":false,"attempts_left":false}

I've disabled the throttle just whilst I get it right.

**Comment by monsterdream** [comment]
Interesting, for example I'm getting empty "message" response and putting correct pin, still doesn't work. Interesting is also that show_attempts_left is set to true but I can't see any message saying that I have some attempts left. Laravel 5.5

![Image](https://cl.ly/2g2Q0E1I2y12/download/Image%202018-02-09%20at%202.39.58%20PM.png)

**Comment by larsjanssen6** [comment]
@monsterdream please make sure u require version 1.3 👍  Let me know if that works!

**Comment by monsterdream** [comment]
@larsjanssen6 Hi! Not really, take a look below. Exceptions is thrown at DebugBar, maybe this will help you find a reason.


![Image](https://cl.ly/3v3V1q2U2I31/download/Image%202018-02-09%20at%203.28.26%20PM.png)

**Comment by larsjanssen6** [comment]
@monsterdream HI!, this is a csrf exception I guess it has nothing to do with my package. When you uncommend:

```
\App\Http\Middleware\VerifyCsrfToken::class
```

in ```kernel.php``` does it then work?

**Comment by monsterdream** [comment]
Hmm at least I can see attempts now, but still giving correct pin is not letting me through. And really I don't think that it could be related to my app, it's working fine on 3 servers and never had that exception before. I will try on new Laravel installation, we will se.

**Comment by larsjanssen6** [comment]
@monsterdream 👍 keep me posted.

**Comment by gsabater** [comment]
I'm also having issues with CSRF token, for some reason the site keeps telling me the csrf is wrong, and i need to remove all cookies to refresh the session again and get a good csrf token.

Seems like the under construction site caches the wrong csrf

**Comment by joscelyn** [comment]
Got the same !
I've needed to remove my cookies to made it work
