### ISSUE TITLE
Dynamic redirect-url

### ISSUE THREAD

**Issue by loic-lopez** [larsjanssen6/underconstruction#46]
Hi, 

It is possible to set a dynamic url like the previous requested url?

**Examples:**
_requested url:_ `http://localhost/user`
_underconstruction package url:_ `http://localhost/under/construction`
_redirect-url:_ `http://localhost/user`

Thanks for reply.

**Comment by larsjanssen6** [comment]
@loic-lopez hi, could you explain that a bit better please ;)

**Comment by loic-lopez** [comment]
Thanks again for reply :)

like the laravel feature of redirecting: 
`return redirect()->intended('defaultpage');`

**Comment by larsjanssen6** [comment]
@loic-lopez no plans for doing this sorry !
