### ISSUE TITLE
When setting the code for the first time, the check won't work

### ISSUE THREAD

**Issue by stefanschindler** [larsjanssen6/underconstruction#48]
Hi,

when setting the code initially (= .env key did not exist previously), it won't work, if the generated hash contains `$` signs.
The reason is, that the string is written to the `.env` files with the `$` escaped.

Example for `APP_KEY=base64:aPAE16A9nSnU1rYuYP3VO0PsqJCthiPf65LiDJ9Jy9Y=`:

`php artisan code:set 1234` produces the hash `$2y$10$1m1s5937qMF6IAJmPdu4DOdSd4j3NxNS1KZGVH.eNZ41LrBCYx0vO`

But the entry in the .env files reads as:
`UNDER_CONSTRUCTION_HASH=\$2y\$10\$zUkU2HgW7VeE2NttFx8wqe3kpanunYOh9joUlJTScSjv.Jx/JF9Di` (note the escaped `$` signs)

When calling the `code:set` command a second time, the hash is correctly written into the .env file

**Comment by larsjanssen6** [comment]
Fixed now.
