### ISSUE TITLE
Feature request - redirection back to the desired URL

### ISSUE THREAD

**Issue by UnrulyNatives** [larsjanssen6/underconstruction#61]
While the config `'redirect-url' => '/',` does the job, a redirection to URL where the user met with PIN panel would be much nicer.

Are you planning to develop the feature?

**Comment by larsjanssen6** [comment]
Could you explain that a bit better please? Thanks!

**Comment by serich159** [comment]
Speaking for myself here, but what I was looking for is if someone goes to the `/abc` route, then gets redirected to enter the pin, is there a way that instead of going to the `'redirect-url' => '/'` config option, they would go to the originally requested `/abc` ?

**Comment by larsjanssen6** [comment]
@serich159 not planned at the moment :)

**Comment by vesper8** [comment]
I wish you would reconsider this @larsjanssen6 .. this should be rather easy to do by setting the intended url in the session and then redirecting to the intended url after a correct code has been entered

I, like many others I assume, am using this to protect several routes, not just one.. so always redirecting to "/" is not desirable in these cases

would you accept a PR?

EDIT: Added a PR https://github.com/larsjanssen6/underconstruction/pull/68
