### ISSUE TITLE
Improve readme file (I'm not a native english speaker :) )

### ISSUE THREAD

**Issue by larsjanssen6** [larsjanssen6/underconstruction#7]

**Comment by teohxuen** [comment]
This Laravel packages makes it possible to set your website in "Under Construction" mode. Only users with the correct 4 digits code can have access to your site. This package could be useful for you to show your website to a specific client. Everything works out of the box, and it's fully customizable.

I made a few mistakes, i think you can change the above to:

"This Laravel package makes it possible for you to set your website in "Under Construction" mode. Only users with the correct 4 digits code can access your site. This package can be useful for you to show your website to a specific client. Everything works out of the box, and it's fully customizable."
