### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by sadekd** [larsjanssen6/underconstruction#73]
Hi, 
using in global web routes group for closing all web routes

Kernel.php:
```
    protected $middlewareGroups = [
        'web' => [
            \LarsJanssen\UnderConstruction\UnderConstruction::class,
```
causing `ERR_TOO_MANY_REDIRECTS`

described: https://github.com/larsjanssen6/underconstruction/issues/64
fixed: https://github.com/larsjanssen6/underconstruction/pull/65/commits/e6f918e585bc499637f5ac719b8487ae317ca42e
bugback: https://github.com/larsjanssen6/underconstruction/commit/2cac2fd7b9d43cf74f38904b613fd66dd030bbba#diff-f06efd90f83aa537b1495807f5ca175d

:crying_cat_face:

**Comment by larsjanssen6** [comment]
@sadekd Thanks fixed now.
