### ISSUE TITLE
vue standalone version (vue-only)

### ISSUE THREAD

**Issue by vesper8** [larsjanssen6/underconstruction#79]
I really love this package and use it extensively. More and more however my front-ends are vue-only and I only use Laravel as a rest api.

I find myself craving for this package's functionality in my vue-only projects. It would be cool to release a vue-only that isn't dependant on php/laravel.

I don't think it should be very hard to do but maybe I'm missing something? What are your thoughts?

**Comment by vesper8** [comment]
well I decided to take a stab at it myself and am pleasantly surprised to see that it already works as a standalone vue component

I just grabbed the UnderConstruction and Loader components and stuck them in my vue-cli pwa. My axios instance there already directs all api requests to my laravel rest api, where this package is installed

so the code verification and everything works via your api. Only thing I had to do was add 'under/*' to the csrf exception array since my vue-cli frontend doesn't use that

only other modification was using vuex-persistedstate to set/store that the page has been "unlocked" upon entering a valid code

**Comment by larsjanssen6** [comment]
@vesper8 yeah you basically can copy the .vue file and build your own implementation. No plans on extracting this to a js package for now. 

If you have other questions please let me know.
