### ISSUE TITLE
multiple valid codes / different codes for different routes

### ISSUE THREAD

**Issue by vesper8** [larsjanssen6/underconstruction#80]
building further on the usability of this package.. I am wondering what are your thoughts on how feasible it would be to add multiple valid codes, or associate certain codes with certain routes

the reason is, I use this package in my project for two reasons, for the intended reason to wall off 'in development' portions of the site for clients, but also to protect admin areas. And I would ideally prefer to use different codes so I can keep my admin area protected while giving access to certain front-end portions for the clients to see

I'd be willing to submit a PR for this but would like to hear your thoughts on what you think the best way to accomplish this would be?

thanks for your consideration!

**Comment by larsjanssen6** [comment]
Hey @vesper8 

Cool that you are using this package a lot 👍 

I like your idea but I always wanted this package
to be very simple. Maybe this should be a separated package?
