### ISSUE TITLE
upload project errors -laravel 5.5

### ISSUE THREAD

**Issue by ibrahimMH13** [larsjanssen6/underconstruction#81]
hay 
the underconstruction package its work normally and useing pin correct but when upload to live hosting cpanel
the same pin not working ???
say the pin its incorrect whenever on local working normally with the same project and pin

**Comment by larsjanssen6** [comment]
You should run the `php artisan code:set` command on your server. And not copy the code from your `.env` file. It's a unique key generated based on your application encryption key!

I guess you can't run artisan command's because you are on `cpanel`?
