### ISSUE TITLE
what would cause it to constantly forget that i'm "authorized" ?

### ISSUE THREAD

**Issue by vesper8** [larsjanssen6/underconstruction#86]
For over a year now I've used this package for means that it was probably not intended for. I use it to secure my access to things like Laravel Horizon, Laravel Telescole and Laravel Log Viewer.

It works.. but it constantly.. and randomly it seems, forgets that I'm authorized shows me the screen again. For example I'll access Laravel Horizon.. I'll get to browse around for 20 seconds and then everything will stop working, and upon refreshing the page I'll be asked to enter the PIN again.

But sometimes it lets me browse for longer.. why is this happening? Is it because the session is not being persisted and as soon as Laravel Horizon attempts to make API calls in the background, on the same route that is protected by your middleware, it triggers the security check to re-occur?

I know this is out of scope, but I would appreciate your feedback on why this is happening and how to stop it from happening, so that I only have to enter the PIN once.. at least for a while.. like a few hours

Thanks in advance!

**Comment by vesper8** [comment]
I would like to add that I am also using the web middleware:

```
'middleware' => ['web', 'under-construction'],
```

so this shouldn't be related to https://github.com/larsjanssen6/underconstruction/pull/2

**Comment by larsjanssen6** [comment]
@vesper8 do you still have this problem?

**Comment by vesper8** [comment]
Honestly yes.. this problem was becoming worse and worse, I eventually gave up protecting my routes with the under-construction middleware for things such as the Telescope or Horizon dashboard. I reverted to using a normal authentication guard in front of those. When using your middleware it would let me through to the page but then if I refreshed the page it would ask me for the code again, again and again, even though I was using the web middleware so sessions were definitely enabled on those routes

**Comment by larsjanssen6** [comment]
@vesper8 that's weird behaviour let me investigate this in the coming days.

**Comment by larsjanssen6** [comment]
@vesper8 hey! I've done some tests with nova and horizon but I can't replicate your issue. Do you have this issue in different projects ?

**Comment by vesper8** [comment]
hrm.. weird.. yes it was happening in my two main projects.. both of them are built very similarly and use a lot of the same dependencies. Well if you can't reproduce it then it must be something on my end. Thanks for looking into it.
