### ISSUE TITLE
404 on http//mysite/under/js

### ISSUE THREAD

**Issue by beuzathor** [larsjanssen6/underconstruction#88]
Hi,
I don't know why but this morning one of my site under production don't want to show anything on the login page.
When i go to the website i have white page with no error in the debugbar. There is a  404 for this request url  https://www.mysite.com/under/js
Very strange beacause yesterday everything was ok.

For the same site in local/dev no problem.

I cleared session, cache, view, route and config. Desinstall/reinstall all the package but nothing.

Did you have this probleme before ?

**Comment by larsjanssen6** [comment]
Please provide dan example. Closing for now.
