### ISSUE TITLE
Improve my sass (only 70 lines)

### ISSUE THREAD

**Issue by larsjanssen6** [larsjanssen6/underconstruction#9]
https://github.com/larsjanssen6/underconstruction/blob/master/resources/assets/UnderConstruction.vue

**Comment by siwalikm** [comment]
raised a pr => https://github.com/larsjanssen6/underconstruction/pull/10

**Comment by larsjanssen6** [comment]
Thanks great improvements!

**Comment by siwalikm** [comment]
@larsjanssen6 looking forward to any help on this issue =>  https://github.com/siwalikm/coffitivity-offline/issues/1
