### ISSUE TITLE
addition of custom prefix has broken access to routes that are more than one level deep

### ISSUE THREAD

**Issue by vesper8** [larsjanssen6/underconstruction#94]
Previoulsy when I would try to goto example.com/log-viewer/logs it would send me to example.com/under/construction, I would enter the pin and it would send me back to example.com/log-viewer/logs

This still works if I try to goto example.com/log-viewer

But if I try to go to a route that's two level deeps.. such as example.com/log-viewer/logs or example.com/horizon/dashboard

Then it will redirect me to example.com/log-viewer/under/construction

completely broken.. was working fine before

**Comment by larsjanssen6** [comment]
@vesper8 thanks for letting me know! This is fixed now.
