### ISSUE TITLE
After installing nothing showing 

### ISSUE THREAD

**Issue by rebarhama** [larsjanssen6/underconstruction#95]
after installing nothing showing
![pin1](https://user-images.githubusercontent.com/15612061/74584992-444b9600-4fe9-11ea-985d-1cdb15580011.PNG)
![pin2](https://user-images.githubusercontent.com/15612061/74584993-46155980-4fe9-11ea-840a-a1cfc79ecfe1.PNG)

**Comment by tsapina** [comment]
I have same problem ... 
js url  is wrong: /under/js/

**Comment by larsjanssen6** [comment]
@rebarhama when I do a clean install it it's working. Looks like your setup is wrong? Do you have it working now ?

**Comment by larsjanssen6** [comment]
@rebarhama closing it for now please let me know I it needs to be reopened.
