### ISSUE TITLE
Url Not Found Issue After Installation

### ISSUE THREAD

**Issue by Salman937** [larsjanssen6/underconstruction#96]
First You Did great work. I did fresh install your package when added the middleware its redirect me and gives me 404 URL not found an error you can see in the below screenshot.

<img width="1440" alt="Screenshot 2020-02-22 at 3 09 30 PM" src="https://user-images.githubusercontent.com/17870239/75090517-8a729d80-5585-11ea-9fe4-9d1b5348110e.png">

**Comment by larsjanssen6** [comment]
@Salman937 hey! please let me know what version you are using. When I do a clean install it works.
