### ISSUE TITLE
NEW Too many redirects

### ISSUE THREAD

**Issue by skywalkerAlex** [larsjanssen6/underconstruction#97]
Hello thanks for your code!
I face the ERR_TOO_MANY_REDIRECTS.
I tried to fix it with the #64 solution but with no luck.
Note that i have localization in active.

In attached files you will find my web.php code
[web.txt](https://github.com/larsjanssen6/underconstruction/files/4344712/web.txt)

Tell me if you need anymore information.
Thanks for your time!!

**Comment by larsjanssen6** [comment]
isn't your problem this line? :

```
Route::redirect('/', '/travelSmartApp/public/en');
```

**Comment by skywalkerAlex** [comment]
> isn't your problem this line? :
> 
> ```
> Route::redirect('/', '/travelSmartApp/public/en');
> ```

Hello, Sorry for my (very) late response and a Big Thank you for your quick response!
I removed my redirection and now has an other problem.
Error
Call to a member function middleware() on null

I am sending you the files [web.txt](https://github.com/larsjanssen6/underconstruction/files/4465999/web.txt) [Kernel.txt](https://github.com/larsjanssen6/underconstruction/files/4466000/Kernel.txt)

what I should do to fix this problem?
Again Thank you very much!

**Comment by larsjanssen6** [comment]
@skywalkerAlex what does your log say?

**Comment by skywalkerAlex** [comment]
i made some changes and now i see the Under Constration page.

I am using Laragon to run my Laravel app and when i enable "Under Constraction" page then sows the "ERR_TOO_MANY_REDIRECTS" error in http://localhost:7000/.
When i run the php artisan serve my app opens in http://localhost:8000/ and the "Under Constraction" is shown correctly. But when i put my pass code it redirects me again to "Under Constraction" page and this is going in loop. 
Also when i disable the "Under Constraction" page then in http://localhost:8000/ it redirects me again in "Under Constraction" page as was on enable and in http://localhost:7000/ it is correctly disable. 
[web.txt](https://github.com/larsjanssen6/underconstruction/files/4496330/web.txt)
 
Does not write anything in Logs.

**Comment by skywalkerAlex** [comment]
Do you have any update?
Do you want to share any files to investigate? 
I took update to the latest version 6.1

**Comment by larsjanssen6** [comment]
@skywalkerAlex hey! I can't replicate your problem. How does your under-construction config file look like?

**Comment by skywalkerAlex** [comment]
I have removed any other redirection.
Here is the under-construction config.
[UNder-Constraction.txt](https://github.com/larsjanssen6/underconstruction/files/4582198/UNder-Constraction.txt)

**Comment by skywalkerAlex** [comment]
I did all the instructions all over again.
But the same proble exists. "ERR_TOO_MANY_REDIRECTS"
Please for your help.

**Comment by larsjanssen6** [comment]
@skywalkerAlex Sorry for the late reaction. Closing for now because I can't simulate this problem.
