### ISSUE TITLE
Disable selectable button labels

### ISSUE THREAD

**Issue by roenfeldt** [larsjanssen6/underconstruction#98]
Awesome package, I just love it @larsjanssen6! The only thing I don't like, is the fact that the buttons' labels can be selected, and it stays selected, even when unintentionally selected. For the record, I'm on a MacBook Pro, using the built-in trackpad. See below.
![Screen Shot 2020-03-18 at 22 24 52](https://user-images.githubusercontent.com/60813178/77010201-a17c9380-6969-11ea-9bb2-9c9627e37d2e.png)
This annoying thing happens very often, when I'm clicking any of the buttons. Is there any way that you can update the package, so that the buttons' label elements have attached the CSS declarations below?
`-webkit-user-select: none;
-moz-user-select: none;
-ms-user-select: none;
user-select: none;`

Thanks a lot.

**Comment by larsjanssen6** [comment]
@roenfeldt sure can you make a PR?

**Comment by roenfeldt** [comment]
@larsjanssen6 I'd love to, but I must confess that I'm pretty new to GitHub, still trying to learn the ropes around here =) and, as an unfortunate consequence, I ended up at the **Compare changes** screen. I've got no clue about what do do further. I'd highly appreciate any help.

**Comment by roenfeldt** [comment]
@larsjanssen6 I tried to figure out the issue on my own, by digging into the code of the `vendor/larsjanssen6/underconstruction/resources/assets/UnderConstruction.vue` file, and adding the CSS rules below [line 352](https://github.com/larsjanssen6/underconstruction/blob/2026d12acfad0c6a47736b5551a5bbf78fe4a817/resources/assets/UnderConstruction.vue#L352) but it doesn't seem to produce any results. Is it even the appropriate place to do it?

I've never worked with Vue - apologies if my question is ridiculous.

**Comment by larsjanssen6** [comment]
@roenfeldt hey, I will add it tomorrow 👍

**Comment by larsjanssen6** [comment]
* in the next coming days :)

**Comment by larsjanssen6** [comment]
@roenfeldt hey! it's fixed now see:

https://github.com/larsjanssen6/underconstruction/commit/90c1a4d9e202924e1ba0ab4465a94b223db3e3fe

Don't forget to run `composer update` 😉

**Comment by roenfeldt** [comment]
> @roenfeldt hey! it's fixed now see:
> 
> [90c1a4d](https://github.com/larsjanssen6/underconstruction/commit/90c1a4d9e202924e1ba0ab4465a94b223db3e3fe)
> 
> Don't forget to run `composer update` 😉

Outstanding ⭐️ One coffee coming your way 😊

**Comment by larsjanssen6** [comment]
@roenfeldt That's awesome! Thanks a lot
